# Generated by Django 5.2.6 on 2026-09-14 22:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS btree_gist;",
            "DROP EXTENSION IF EXISTS btree_gist;",
        ),
        migrations.CreateModel(
            name='PeriodoProgramacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('timezone', models.CharField(max_length=64)),
                ('current_publication_id', models.UUIDField(blank=True, null=True)),
                ('edit_revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organizacion')),
            ],
        ),
        migrations.CreateModel(
            name='BorradorProgramacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_publication_id', models.UUIDField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organizacion')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='draft', to='programacion.periodoprogramacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AsignacionJornada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='core.asignacion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organizacion')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programacion.periodoprogramacion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicacionProgramacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('previous_publication_id', models.UUIDField(blank=True, null=True)),
                ('publisher_label', models.CharField(max_length=200)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('branch_label', models.CharField(max_length=200)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('timezone', models.CharField(max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organizacion')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programacion.periodoprogramacion')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JornadaPublicada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_id', models.UUIDField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('start_local', models.DateTimeField()),
                ('end_local', models.DateTimeField()),
                ('start_offset', models.IntegerField()),
                ('end_offset', models.IntegerField()),
                ('timezone', models.CharField(max_length=64)),
                ('role_id', models.UUIDField(blank=True, null=True)),
                ('station_id', models.UUIDField(blank=True, null=True)),
                ('shift_id', models.UUIDField(blank=True, null=True)),
                ('labels', models.JSONField(default=dict)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.asignacion')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empleado')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organizacion')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='programacion.publicacionprogramacion')),
            ],
        ),
        migrations.CreateModel(
            name='FilaEmpleadoPublicada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_label', models.CharField(max_length=200)),
                ('display_order', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empleado')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organizacion')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster', to='programacion.publicacionprogramacion')),
            ],
        ),
        migrations.CreateModel(
            name='DescansoPublicado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('break_id', models.UUIDField()),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('start_local', models.DateTimeField()),
                ('end_local', models.DateTimeField()),
                ('start_offset', models.IntegerField()),
                ('end_offset', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.asignacion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organizacion')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breaks', to='programacion.publicacionprogramacion')),
            ],
        ),
        migrations.CreateModel(
            name='DescansoBorrador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('start_local', models.DateTimeField()),
                ('end_local', models.DateTimeField()),
                ('start_offset', models.IntegerField()),
                ('end_offset', models.IntegerField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.asignacion')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breaks', to='programacion.borradorprogramacion')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organizacion')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='schedule_break_positive_interval')],
            },
        ),
        migrations.CreateModel(
            name='JornadaBorrador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('start_local', models.DateTimeField()),
                ('end_local', models.DateTimeField()),
                ('start_offset', models.IntegerField()),
                ('end_offset', models.IntegerField()),
                ('timezone', models.CharField(max_length=64)),
                ('labels', models.JSONField(default=dict)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.asignacion')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal')),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='programacion.borradorprogramacion')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.empleado')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.organizacion')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.rol')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.turno')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.estacion')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'employee', 'starts_at', 'ends_at'], name='programacio_organiz_305743_idx')],
                'constraints': [models.UniqueConstraint(fields=('draft', 'assignment'), name='schedule_draft_assignment_uniq'), models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='schedule_draft_positive_interval')],
            },
        ),
        migrations.AddIndex(
            model_name='periodoprogramacion',
            index=models.Index(fields=['organization', 'branch', 'date_from', 'date_to'], name='programacio_organiz_75e914_idx'),
        ),
        migrations.AddConstraint(
            model_name='periodoprogramacion',
            constraint=models.CheckConstraint(condition=models.Q(('date_to__gte', models.F('date_from'))), name='schedule_period_dates_ordered'),
        ),
        migrations.RunSQL(
            "ALTER TABLE programacion_periodoprogramacion ADD CONSTRAINT schedule_period_branch_no_overlap EXCLUDE USING gist (organization_id WITH =, branch_id WITH =, daterange(date_from, date_to, '[]') WITH &&);",
            "ALTER TABLE programacion_periodoprogramacion DROP CONSTRAINT IF EXISTS schedule_period_branch_no_overlap;",
        ),
        migrations.AddConstraint(
            model_name='publicacionprogramacion',
            constraint=models.UniqueConstraint(fields=('period', 'version'), name='schedule_publication_version_uniq'),
        ),
        migrations.AddConstraint(
            model_name='jornadapublicada',
            constraint=models.UniqueConstraint(fields=('publication', 'assignment'), name='schedule_snapshot_assignment_uniq'),
        ),
        migrations.AddConstraint(
            model_name='filaempleadopublicada',
            constraint=models.UniqueConstraint(fields=('publication', 'employee'), name='schedule_publication_employee_uniq'),
        ),
        migrations.AddConstraint(
            model_name='descansopublicado',
            constraint=models.UniqueConstraint(fields=('publication', 'break_id'), name='schedule_snapshot_break_uniq'),
        ),
    ]
