# Generated manually from the Core domain models; equivalent to Django 5.2 makemigrations.
import uuid
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="Organizacion", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("name", models.CharField(max_length=200)), ("core_revision", models.PositiveBigIntegerField(default=0)), ("created_at", models.DateTimeField(auto_now_add=True))]),
        migrations.CreateModel(name="Empleado", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("display_name", models.CharField(max_length=200)), ("active", models.BooleanField(default=True)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.organizacion"))]),
        migrations.CreateModel(name="Sucursal", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("name", models.CharField(max_length=200)), ("timezone", models.CharField(max_length=64)), ("active", models.BooleanField(default=True)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.organizacion"))]),
        migrations.CreateModel(name="Area", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("name", models.CharField(max_length=200)), ("active", models.BooleanField(default=True)), ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.sucursal")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.organizacion"))]),
        migrations.CreateModel(name="Asignacion", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("kind", models.CharField(default="jornada", max_length=32)), ("created_at", models.DateTimeField(auto_now_add=True)), ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.organizacion"))]),
        migrations.CreateModel(name="Rol", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("name", models.CharField(max_length=200)), ("active", models.BooleanField(default=True)), ("applicable_branches", models.ManyToManyField(blank=True, to="core.sucursal")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.organizacion"))]),
        migrations.CreateModel(name="Turno", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("name", models.CharField(max_length=200)), ("active", models.BooleanField(default=True)), ("start_local_time", models.TimeField()), ("end_local_time", models.TimeField()), ("end_day_offset", models.PositiveSmallIntegerField(default=0)), ("applicable_branches", models.ManyToManyField(blank=True, to="core.sucursal")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.organizacion"))]),
        migrations.CreateModel(name="Estacion", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("name", models.CharField(max_length=200)), ("active", models.BooleanField(default=True)), ("area", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.area")), ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.sucursal")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.organizacion"))]),
        migrations.CreateModel(name="HabilitacionSucursal", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("enabled", models.BooleanField(default=True)), ("changed_at", models.DateTimeField(auto_now=True)), ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.sucursal")), ("changed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)), ("employee", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.empleado")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.organizacion"))], options={"constraints": [models.UniqueConstraint(fields=("employee", "branch"), name="core_employee_branch_enable_uniq")]}),
        migrations.CreateModel(name="UsuarioOrganizacion", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("active", models.BooleanField(default=True)), ("employee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.empleado")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.organizacion")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL))], options={"constraints": [models.UniqueConstraint(fields=("user", "organization"), name="core_user_org_uniq")]}),
        migrations.CreateModel(name="PermisoPlaneacion", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("enabled", models.BooleanField(default=True)), ("branch", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.sucursal")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.organizacion")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL))], options={"constraints": [models.UniqueConstraint(fields=("user", "branch"), name="core_planner_grant_uniq")]}),
        migrations.CreateModel(name="Evento", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("type", models.CharField(max_length=100)), ("subject_id", models.UUIDField()), ("payload", models.JSONField(default=dict)), ("occurred_at", models.DateTimeField(auto_now_add=True)), ("correlation_id", models.UUIDField(default=uuid.uuid4)), ("actor", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)), ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.sucursal")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.organizacion"))]),
        migrations.CreateModel(name="Auditoria", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("operation", models.CharField(max_length=100)), ("subject_id", models.UUIDField()), ("before", models.JSONField(blank=True, null=True)), ("after", models.JSONField(blank=True, null=True)), ("outcome", models.CharField(default="success", max_length=32)), ("occurred_at", models.DateTimeField(auto_now_add=True)), ("correlation_id", models.UUIDField(default=uuid.uuid4)), ("actor", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)), ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.sucursal")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.organizacion"))]),
        migrations.CreateModel(name="Incidencia", fields=[("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ("period_id", models.UUIDField()), ("type", models.CharField(max_length=100)), ("affected_assignment_ids", models.JSONField(default=list)), ("status", models.CharField(default="open", max_length=32)), ("resolved_at", models.DateTimeField(blank=True, null=True)), ("occurred_at", models.DateTimeField(auto_now_add=True)), ("correlation_id", models.UUIDField(default=uuid.uuid4)), ("actor", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)), ("branch", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.sucursal")), ("employee", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="core.empleado")), ("organization", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="core.organizacion")), ("resolution_event", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="resolved_incidents", to="core.evento")), ("source_event", models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name="source_incidents", to="core.evento"))]),
    ]
